---
- name: Jenkins | download apt key for jenkins repository
  apt_key:
    url=https://jenkins-ci.org/debian/jenkins-ci.org.key
    state=present

- name: Jenkins | add jenkins APT repository
  apt_repository:
    repo='deb http://pkg.jenkins-ci.org/debian binary/'
    state=present

- name: Jenkins | Install jenkins
  apt:
    pkg=jenkins
    update_cache=yes
    force=yes
    state=latest
  notify: 
    - Start jenkins

- name: Jenkins | Install ant
  apt:
    pkg=ant
    update_cache=yes
        
